image: Visual Studio 2019
version: '{build}'
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: MiniProfiler.Elasticsearch.sln
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
artifacts:
- path: /src/**/*.nupkg
  name: nuget
- path: /src/**/*.nupkg
  name: nuget
deploy:
- provider: NuGet
  api_key:
    secure: OAMDfki9Rf05xrPNsh1ZoCUF9zTPOpZQAp0ebc8cou98USUq2QQciuDLZBnEjwp2
  on:
    APPVEYOR_REPO_TAG: true
